### ISSUE TITLE
一个小细节

### ISSUE THREAD

**Issue by 15601560** [1834423612/Moe-counter-PHP#2]
我看你PHP是调用theme的图片
建议base64编码图片

**Comment by 15601560** [comment]
这样减少一个图片的 HTTP 请求
减少服务器负担
不然每个都去访问一次img文件夹在大流量下会导致服务器吃不消

**Comment by 15601560** [comment]
还有尝试下mysql？毕竟这样处理只能适用于自己而且效率底下

**Comment by 1834423612** [comment]
好的，谢谢建议，下个版本准备优化

**Comment by 8680** [comment]
现在初中生这么顶吗:muscle:

**Comment by 1834423612** [comment]
> 还有尝试下mysql？毕竟这样处理只能适用于自己而且效率底下

目前已更新，升级到了 PHP + Mysql
