### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by imgblz** [1834423612/Moe-counter-PHP#3]
MC的数字1格格不入，左边加一点点空白透明边

**Comment by imgblz** [comment]
图片可以使用jsdelivr、---cdn.jsdelivr.net改成js.imgblz.cn或者jsdelivr.imgblz.cn

**Comment by 1834423612** [comment]
@imgblz 感谢反馈，目前已经修改完毕并已合并至主分支。目前调用图片仍然为base64，jsdelivr后续会测试添加为可自定义配置选项😄
